workflows:
  ios-workflow:
    name: Build iOS App with Codemagic Certs
    environment:
      vars:
        NODE_VERSION: 18.16.0
        XCODE_VERSION: latest
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install dependencies
        script: npm install --legacy-peer-deps
      - name: Build the web assets
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Build iOS project
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $HOME/output/App.xcarchive \
            archive
      - name: Export iOS .ipa
        script: |
          xcodebuild -exportArchive \
            -archivePath $HOME/output/App.xcarchive \
            -exportOptionsPlist $CM_EXPORT_OPTIONS_PLIST \
            -exportPath $HOME/output
    artifacts:
      - $HOME/output/*.ipa
      - $HOME/output/*.xcarchive
    publishing:
      email:
        recipients:
          - petr@prikryl.cc
